"use client";
import { FormEvent, useEffect, useState } from "react";
import { getSupabaseBrowser } from "../../lib/supabase-browser";

export default function Onboarding(){
 const[company,setCompany]=useState("");const[phone,setPhone]=useState("");const[email,setEmail]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{getSupabaseBrowser().auth.getUser().then(({data})=>{if(data.user){setEmail(data.user.email||"");setCompany(data.user.user_metadata?.company_name||"")}})},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const {data:{user}}=await getSupabaseBrowser().auth.getUser();if(!user)throw new Error("Please sign in again");const r=await fetch("/api/company",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({companyName:company,phone,email})});const x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||"Unable to save company");window.location.href="/"}catch(e){setError(e instanceof Error?e.message:"Unable to save setup")}finally{setBusy(false)}}
 return <main style={s.page}><div style={s.card}><div style={s.logo}><span>Q</span> QuoteFlow</div><div style={s.step}>STEP 1 OF 1</div><h1>Set up your business</h1><p>These details appear on your QuoteFlow workspace.</p>{error&&<div style={s.error}>{error}</div>}<form onSubmit={submit}><label>Company name<input required value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Business phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Business email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button disabled={busy}>{busy?"Saving...":"Finish setup"}</button></form></div></main>
}
const s={page:{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f7f8fa",fontFamily:"Inter,system-ui,sans-serif",padding:20},card:{width:"100%",maxWidth:480,background:"white",border:"1px solid #e3e7ed",borderRadius:14,padding:34},logo:{fontSize:19,fontWeight:800,display:"flex",gap:9,alignItems:"center",marginBottom:28},step:{fontSize:9,fontWeight:800,letterSpacing:1.5,color:"#9ca3af"},h1:{fontSize:28,margin:"8px 0"},p:{color:"#6b7280",fontSize:13,margin:"0 0 24px"},label:{display:"block",fontSize:11,fontWeight:700,color:"#374151",marginBottom:14},input:{display:"block",width:"100%",marginTop:6,padding:11,border:"1px solid #d9dee6",borderRadius:8,boxSizing:"border-box"},button:{width:"100%",padding:12,border:0,borderRadius:8,background:"#111827",color:"white",fontWeight:700},error:{padding:11,borderRadius:8,background:"#fff1f2",color:"#be123c",fontSize:12,marginBottom:14}};
