"use client";

import { useEffect, useMemo, useState } from "react";

type Lead={id:string;name:string;phone:string|null;email:string|null;service:string|null;status:string|null;"appointment date":string|null};
const statuses=["New","Contacted","Quoted","Scheduled","Completed","Cancelled"];
const nav={color:"#64748b",textDecoration:"none",fontSize:"13px",fontWeight:400} as const;

export default function AppointmentsPage(){
 const[leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState("Upcoming"),[saving,setSaving]=useState<string|null>(null);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/leads",{cache:"no-store"}),x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||"Unable to load appointments");setLeads(x.data||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load appointments")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 const appointments=useMemo(()=>leads.filter(l=>!!l["appointment date"]).sort((a,b)=>new Date(a["appointment date"]!+"T00:00:00").getTime()-new Date(b["appointment date"]!+"T00:00:00").getTime()),[leads]);
 const today=new Date();today.setHours(0,0,0,0);const upcoming=appointments.filter(l=>new Date(l["appointment date"]!+"T00:00:00")>=today),past=appointments.filter(l=>new Date(l["appointment date"]!+"T00:00:00")<today);const shown=filter==="Upcoming"?upcoming:filter==="Past"?past:appointments;
 async function update(id:string,fields:Record<string,unknown>){setSaving(id);setError("");try{const r=await fetch("/api/leads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...fields})}),x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||"Unable to update appointment");const u=x.data?.[0];if(u)setLeads(v=>v.map(l=>l.id===id?u:l))}catch(e){setError(e instanceof Error?e.message:"Unable to update appointment")}finally{setSaving(null)}}
 return <main style={s.page}><div style={s.container}><nav style={s.nav}><a href="/" style={s.logo}>QuoteFlow</a><div style={s.links}><a href="/" style={nav}>Dashboard</a><a href="/leads" style={nav}>Leads</a><a href="/quotes" style={nav}>Quotes</a><a href="/appointments" style={nav}>Appointments</a></div><a href="/leads/new" style={s.button}>+ New Lead</a></nav><div style={s.header}><div><h1 style={s.title}>Appointments</h1><p style={s.muted}>Schedule and manage customer jobs.</p></div><div style={s.total}>{upcoming.length} upcoming</div></div><div style={s.stats}><div style={s.stat}><span>Total</span><strong>{appointments.length}</strong></div><div style={s.stat}><span>Upcoming</span><strong>{upcoming.length}</strong></div><div style={s.stat}><span>Past</span><strong>{past.length}</strong></div></div><div style={s.toolbar}><button onClick={()=>setFilter("Upcoming")} style={{...s.filter,...(filter==="Upcoming"?s.active:{})}}>Upcoming</button><button onClick={()=>setFilter("All")} style={{...s.filter,...(filter==="All"?s.active:{})}}>All</button><button onClick={()=>setFilter("Past")} style={{...s.filter,...(filter==="Past"?s.active:{})}}>Past</button><button onClick={load} style={s.refresh}>↻ Refresh</button></div>{error&&<div style={s.error}>⚠ {error}</div>}{loading?<div style={s.empty}>Loading appointments...</div>:shown.length===0?<div style={s.empty}><h2>No appointments</h2><p>Set an appointment date on a customer to schedule a job.</p><a href="/leads" style={s.button}>View Leads</a></div>:<div style={s.card}>{shown.map(l=><div key={l.id} style={s.row}><div style={s.date}><b>{new Date(l["appointment date"]!+"T00:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})}</b><span>{new Date(l["appointment date"]!+"T00:00:00").getFullYear()}</span></div><div><a href={`/leads/${l.id}`} style={s.customer}>{l.name}</a><div style={s.small}>{l.service||"HVAC Service"} · {l.phone||l.email||"No contact"}</div></div><select disabled={saving===l.id} value={l.status||"New"} onChange={e=>update(l.id,{status:e.target.value})} style={s.select}>{statuses.map(x=><option key={x}>{x}</option>)}</select><input type="date" defaultValue={l["appointment date"]||""} onBlur={e=>{if(e.target.value!==l["appointment date"])update(l.id,{appointmentDate:e.target.value})}} style={s.dateInput}/><a href={`/leads/${l.id}`} style={s.open}>Open →</a></div>)}</div>}</div></main>}
const s={page:{minHeight:"100vh",background:"#f8fafc",color:"#0f172a",fontFamily:"Inter,ui-sans-serif,system-ui,sans-serif"},container:{maxWidth:"1200px",margin:"0 auto",padding:"0 28px 60px"},nav:{height:"76px",display:"flex",alignItems:"center",justifyContent:"space-between",borderBottom:"1px solid #e2e8f0"},logo:{color:"#0f172a",textDecoration:"none",fontSize:"20px",fontWeight:800},links:{display:"flex",gap:"28px",alignItems:"center"},header:{display:"flex",justifyContent:"space-between",alignItems:"end",padding:"40px 0 24px"},title:{margin:0,fontSize:"32px"},muted:{color:"#64748b",marginTop:"8px",fontSize:"14px"},total:{fontSize:"14px",fontWeight:600},button:{background:"#0f172a",color:"white",textDecoration:"none",padding:"10px 16px",borderRadius:"8px",fontSize:"13px",fontWeight:600},stats:{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:"16px",marginBottom:"18px"},stat:{background:"white",border:"1px solid #e2e8f0",borderRadius:"12px",padding:"18px",display:"flex",justifyContent:"space-between",color:"#64748b",fontSize:"13px"},toolbar:{display:"flex",gap:"8px",marginBottom:"16px"},filter:{border:"1px solid #cbd5e1",background:"white",color:"#64748b",padding:"9px 14px",borderRadius:"8px",cursor:"pointer",fontSize:"13px"},active:{background:"#0f172a",color:"white",borderColor:"#0f172a"},refresh:{marginLeft:"auto",background:"white",border:"1px solid #cbd5e1",borderRadius:"8px",padding:"9px 13px",cursor:"pointer",color:"#334155"},card:{background:"white",border:"1px solid #e2e8f0",borderRadius:"12px",overflow:"hidden"},row:{display:"grid",gridTemplateColumns:"1fr 2fr 1.3fr 1.3fr 70px",gap:"16px",alignItems:"center",padding:"17px 20px",borderBottom:"1px solid #f0f0f0"},date:{display:"flex",flexDirection:"column" as const,fontSize:"14px"},small:{color:"#94a3b8",fontSize:"12px",marginTop:"5px"},customer:{color:"#0f172a",textDecoration:"none",fontWeight:500},select:{padding:"9px",border:"1px solid #cbd5e1",borderRadius:"8px",background:"white",fontSize:"12px"},dateInput:{padding:"8px",border:"1px solid #cbd5e1",borderRadius:"8px",fontSize:"12px"},open:{color:"#475569",textDecoration:"none",fontSize:"11px",fontWeight:600},empty:{background:"white",border:"1px solid #e2e8f0",borderRadius:"12px",padding:"65px 20px",textAlign:"center" as const,color:"#64748b"},error:{padding:"14px 16px",marginBottom:"18px",background:"#fff1f2",color:"#be123c",border:"1px solid #fecdd3",borderRadius:"9px"}};
