"use client";
import { useEffect, useMemo, useState } from "react";

type Lead={id:string;name:string;email:string|null;phone:string|null;service:string|null;status:string|null;"quote amount":number|null;"appointment date":string|null};
const statuses=["New","Contacted","Quoted","Scheduled","Completed","Cancelled"];
export default function QuotesPage(){
 const[leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[saving,setSaving]=useState<string|null>(null);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/leads",{cache:"no-store"}),x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||"Unable to load quotes");setLeads((x.data||[]).filter((l:Lead)=>l["quote amount"]!==null&&l["quote amount"]!==undefined))}catch(e){setError(e instanceof Error?e.message:"Unable to load quotes")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function update(id:string,fields:Record<string,unknown>){setSaving(id);setError("");try{const r=await fetch("/api/leads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...fields})}),x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||"Unable to update quote");const updated=x.data?.[0];if(updated)setLeads(v=>v.map(l=>l.id===id?updated:l))}catch(e){setError(e instanceof Error?e.message:"Unable to update quote")}finally{setSaving(null)}}
 const filtered=useMemo(()=>leads.filter(l=>{const q=search.toLowerCase().trim();return !q||[l.name,l.email,l.phone,l.service].some(v=>(v||"").toLowerCase().includes(q))}),[leads,search]);
 const total=filtered.reduce((n,l)=>n+Number(l["quote amount"]||0),0),won=filtered.filter(l=>l.status==="Completed").reduce((n,l)=>n+Number(l["quote amount"]||0),0);
 return <main style={s.page}><div style={s.container}><Header/><div style={s.header}><div><div style={s.eyebrow}>REVENUE PIPELINE</div><h1 style={s.title}>Quotes</h1><p style={s.muted}>Manage pricing, quote status, and potential revenue.</p></div><div style={s.headerStats}><div><span>Pipeline</span><strong>${total.toLocaleString()}</strong></div><div><span>Completed</span><strong>${won.toLocaleString()}</strong></div></div></div>{error&&<div style={s.error}>⚠ {error}<button onClick={()=>void load()} style={s.retry}>Try again</button></div>}<div style={s.toolbar}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search quotes..." style={s.input}/><button onClick={()=>void load()} style={s.secondary}>↻ Refresh</button></div>{loading?<div style={s.empty}>Loading quotes...</div>:filtered.length===0?<div style={s.empty}><div style={s.emptyIcon}>$</div><h2>No quotes yet</h2><p>Add a quote amount to a lead and it will appear here.</p><a href="/leads" style={s.button}>View Leads</a></div>:<div style={s.grid}>{filtered.map(l=><article key={l.id} style={s.card}><div style={s.top}><div><a href={`/leads/${l.id}`} style={s.customer}>{l.name}</a><div style={s.small}>{l.service||"HVAC Service"}</div></div><div style={s.amount}>${Number(l["quote amount"]).toLocaleString()}</div></div><div style={s.details}>{l.phone||l.email||"No contact"}{l["appointment date"]?` · ${new Date(l["appointment date"]+"T00:00:00").toLocaleDateString()}`:""}</div><label style={s.label}>Quote amount</label><input type="number" min="0" step="0.01" defaultValue={l["quote amount"]??""} onBlur={e=>{const v=e.target.value;if(v!==String(l["quote amount"]??""))void update(l.id,{quoteAmount:v})}} style={s.input}/><label style={s.label}>Status</label><select disabled={saving===l.id} value={l.status||"New"} onChange={e=>void update(l.id,{status:e.target.value})} style={{...s.select,...statusColor(l.status)}}>{statuses.map(x=><option key={x}>{x}</option>)}</select>{saving===l.id&&<div style={s.saving}>Saving...</div>}</article>)}</div>}</div></main>
}
function Header(){return <nav style={s.nav}><a href="/" style={s.logo}><span style={s.logoMark}>Q</span>QuoteFlow</a><div style={s.links}><a href="/" style={s.link}>Dashboard</a><a href="/leads" style={s.link}>Leads</a><a href="/quotes" style={s.active}>Quotes</a><a href="/appointments" style={s.link}>Appointments</a></div><a href="/leads/new" style={s.button}>+ New Lead</a></nav>}
function statusColor(v:string|null){const x=(v||"New").toLowerCase();const c:Record<string,object>={new:{background:"#fff7ed",color:"#c2410c"},contacted:{background:"#eff6ff",color:"#2563eb"},quoted:{background:"#f5f3ff",color:"#7c3aed"},scheduled:{background:"#f0fdf4",color:"#15803d"},completed:{background:"#ecfdf5",color:"#059669"},cancelled:{background:"#f1f5f9",color:"#64748b"}};return c[x]||c.new}
const s={page:{minHeight:"100vh",background:"#f7f8fa",color:"#111827",fontFamily:"Inter,ui-sans-serif,system-ui,sans-serif"},container:{maxWidth:1200,margin:"0 auto",padding:"0 28px 60px"},nav:{height:72,display:"flex",alignItems:"center",gap:28,borderBottom:"1px solid #e5e7eb"},logo:{display:"flex",alignItems:"center",gap:9,color:"#111827",textDecoration:"none",fontSize:19,fontWeight:800},logoMark:{width:30,height:30,display:"grid",placeItems:"center",borderRadius:8,background:"#111827",color:"white",fontSize:14},links:{display:"flex",justifyContent:"center",gap:26,flex:1},link:{color:"#6b7280",textDecoration:"none",fontSize:13,fontWeight:600},active:{color:"#111827",textDecoration:"none",fontSize:13,fontWeight:700,borderBottom:"2px solid #111827",paddingBottom:7},header:{display:"flex",justifyContent:"space-between",alignItems:"end",padding:"40px 0 22px"},eyebrow:{color:"#6b7280",fontSize:10,fontWeight:800,letterSpacing:1.5,marginBottom:7},title:{margin:0,fontSize:32,letterSpacing:-1},muted:{color:"#6b7280",marginTop:7,fontSize:13},headerStats:{display:"flex",gap:25},headerStat:{},toolbar:{display:"flex",gap:10,marginBottom:16},input:{width:"100%",boxSizing:"border-box",padding:"11px 12px",border:"1px solid #d9dee6",borderRadius:8,fontSize:12,background:"white",color:"#111827",outline:"none"},secondary:{background:"white",border:"1px solid #d9dee6",borderRadius:8,padding:"9px 13px",cursor:"pointer",color:"#374151",fontSize:12,fontWeight:700,whiteSpace:"nowrap"},button:{background:"#111827",color:"white",textDecoration:"none",padding:"10px 14px",borderRadius:8,fontSize:12,fontWeight:700,border:0,cursor:"pointer"},grid:{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:16},card:{background:"white",border:"1px solid #e3e7ed",borderRadius:10,padding:19},top:{display:"flex",justifyContent:"space-between",alignItems:"start",gap:15},customer:{color:"#111827",textDecoration:"none",fontWeight:700,fontSize:13},small:{color:"#9ca3af",fontSize:10,marginTop:5},amount:{fontSize:22,fontWeight:800},details:{color:"#6b7280",fontSize:11,margin:"17px 0",paddingBottom:14,borderBottom:"1px solid #f0f2f4"},label:{display:"block",fontSize:10,fontWeight:700,color:"#6b7280",margin:"11px 0 5px"},select:{width:"100%",padding:"10px",border:"1px solid transparent",borderRadius:8,fontSize:12},empty:{background:"white",border:"1px solid #e3e7ed",borderRadius:10,padding:"65px 20px",textAlign:"center",color:"#6b7280",fontSize:13},emptyIcon:{width:36,height:36,display:"grid",placeItems:"center",margin:"0 auto 10px",borderRadius:9,background:"#f3f4f6",fontWeight:800},error:{padding:13,marginBottom:16,borderRadius:8,background:"#fff1f2",color:"#be123c",border:"1px solid #fecdd3",fontSize:12},retry:{marginLeft:10,border:0,background:"none",textDecoration:"underline",cursor:"pointer",color:"inherit"},saving:{fontSize:10,color:"#9ca3af",marginTop:7}};
