"use client";

import { useEffect, useMemo, useState } from "react";

type Lead = { id:string; name:string; email:string|null; phone:string|null; service:string|null; status:string|null; "quote amount":number|null; "appointment date":string|null };
const statuses=["New","Contacted","Quoted","Scheduled","Completed","Cancelled"];
const nav={color:"#64748b",textDecoration:"none",fontSize:"13px",fontWeight:400} as const;

export default function QuotesPage(){
 const [leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[saving,setSaving]=useState<string|null>(null);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/leads",{cache:"no-store"}),x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||"Unable to load quotes");setLeads((x.data||[]).filter((l:Lead)=>l["quote amount"]!==null&&l["quote amount"]!==undefined))}catch(e){setError(e instanceof Error?e.message:"Unable to load quotes")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function update(id:string,fields:Record<string,unknown>){setSaving(id);setError("");try{const r=await fetch("/api/leads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...fields})}),x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||"Unable to update quote");const updated=x.data?.[0];if(updated)setLeads(v=>v.map(l=>l.id===id?updated:l))}catch(e){setError(e instanceof Error?e.message:"Unable to update quote")}finally{setSaving(null)}}
 const filtered=useMemo(()=>leads.filter(l=>{const q=search.toLowerCase();return !q||[l.name,l.email,l.phone,l.service].some(v=>(v||"").toLowerCase().includes(q))}),[leads,search]);
 const total=filtered.reduce((n,l)=>n+Number(l["quote amount"]||0),0);
 return <main style={s.page}><div style={s.container}><nav style={s.nav}><a href="/" style={s.logo}>QuoteFlow</a><div style={s.links}><a href="/" style={nav}>Dashboard</a><a href="/leads" style={nav}>Leads</a><a href="/quotes" style={nav}>Quotes</a><a href="/appointments" style={nav}>Appointments</a></div><a href="/leads/new" style={s.button}>+ New Lead</a></nav>
 <div style={s.header}><div><h1 style={s.title}>Quotes</h1><p style={s.muted}>Manage pricing and quote status.</p></div><div style={s.total}>${total.toLocaleString()} pipeline</div></div>
 <div style={s.toolbar}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search quotes..." style={s.input}/><button onClick={load} style={s.refresh}>↻ Refresh</button></div>{error&&<div style={s.error}>⚠ {error}</div>}
 {loading?<div style={s.empty}>Loading quotes...</div>:filtered.length===0?<div style={s.empty}><h2>No quotes yet</h2><p>Add a quote amount to a lead and it will appear here.</p><a href="/leads" style={s.button}>View Leads</a></div>:<div style={s.grid}>{filtered.map(l=><div key={l.id} style={s.card}><div style={s.top}><div><a href={`/leads/${l.id}`} style={s.customer}>{l.name}</a><div style={s.small}>{l.service||"HVAC Service"}</div></div><div style={s.amount}>${Number(l["quote amount"]).toLocaleString()}</div></div><div style={s.details}>{l.phone||l.email||"No contact"}{l["appointment date"]?` · ${new Date(l["appointment date"]+"T00:00:00").toLocaleDateString()}`:""}</div><label style={s.label}>Quote amount</label><input type="number" min="0" step="0.01" defaultValue={l["quote amount"]??""} onBlur={e=>{const v=e.target.value;if(v!==String(l["quote amount"]??""))update(l.id,{quoteAmount:v})}} style={s.input}/><label style={s.label}>Status</label><select disabled={saving===l.id} value={l.status||"New"} onChange={e=>update(l.id,{status:e.target.value})} style={s.select}>{statuses.map(x=><option key={x}>{x}</option>)}</select>{saving===l.id&&<div style={s.saving}>Saving...</div>}</div>)}</div>}</div></main>
}
const s={page:{minHeight:"100vh",background:"#f8fafc",color:"#0f172a",fontFamily:"Inter,ui-sans-serif,system-ui,sans-serif"},container:{maxWidth:"1200px",margin:"0 auto",padding:"0 28px 60px"},nav:{height:"76px",display:"flex",alignItems:"center",justifyContent:"space-between",borderBottom:"1px solid #e2e8f0"},logo:{color:"#0f172a",textDecoration:"none",fontSize:"20px",fontWeight:800},links:{display:"flex",gap:"28px",alignItems:"center"},header:{display:"flex",justifyContent:"space-between",alignItems:"end",padding:"40px 0 24px"},title:{margin:0,fontSize:"32px"},muted:{color:"#64748b",marginTop:"8px",fontSize:"14px"},total:{fontSize:"14px",fontWeight:600},button:{background:"#0f172a",color:"white",textDecoration:"none",padding:"10px 16px",borderRadius:"8px",fontSize:"13px",fontWeight:600},refresh:{background:"white",border:"1px solid #cbd5e1",borderRadius:"8px",padding:"9px 13px",cursor:"pointer",color:"#334155"},toolbar:{display:"flex",gap:"10px",marginBottom:"16px"},input:{width:"100%",boxSizing:"border-box" as const,padding:"10px 12px",border:"1px solid #cbd5e1",borderRadius:"8px",fontSize:"13px",background:"white"},grid:{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:"16px"},card:{background:"white",border:"1px solid #e2e8f0",borderRadius:"12px",padding:"20px"},top:{display:"flex",justifyContent:"space-between",alignItems:"start",gap:"15px"},customer:{color:"#0f172a",textDecoration:"none",fontWeight:500},small:{color:"#94a3b8",fontSize:"12px",marginTop:"5px"},amount:{fontSize:"22px",fontWeight:700},details:{color:"#64748b",fontSize:"12px",margin:"18px 0"},label:{display:"block",fontSize:"11px",fontWeight:600,color:"#64748b",margin:"12px 0 5px"},select:{width:"100%",padding:"10px",border:"1px solid #cbd5e1",borderRadius:"8px",background:"white",color:"#334155"},empty:{background:"white",border:"1px solid #e2e8f0",borderRadius:"12px",padding:"65px 20px",textAlign:"center" as const,color:"#64748b"},error:{padding:"14px 16px",marginBottom:"18px",background:"#fff1f2",color:"#be123c",border:"1px solid #fecdd3",borderRadius:"9px"},saving:{fontSize:"11px",color:"#64748b",marginTop:"8px"}};
