"use client";
import { FormEvent, useState } from "react";
import { getSupabaseBrowser } from "../../lib/supabase-browser";

export default function SignupPage(){
 const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[company,setCompany]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[done,setDone]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const {data,error}=await getSupabaseBrowser().auth.signUp({email,password,options:{data:{company_name:company}}});if(error)throw error;if(!data.session){setDone(true)}else window.location.href="/onboarding"}catch(e){setError(e instanceof Error?e.message:"Unable to create account")}finally{setBusy(false)}}
 if(done)return <main style={s.page}><div style={s.card}><div style={s.logo}><span>Q</span> QuoteFlow</div><h1>Check your email</h1><p>We sent a confirmation link to <strong>{email}</strong>. Confirm it, then sign in to finish setup.</p><a href="/login" style={s.button}>Go to sign in</a></div></main>;
 return <main style={s.page}><div style={s.card}><div style={s.logo}><span>Q</span> QuoteFlow</div><h1>Create your account</h1><p>Set up QuoteFlow for your HVAC business.</p>{error&&<div style={s.error}>{error}</div>}<form onSubmit={submit}><label>Company name<input required value={company} onChange={e=>setCompany(e.target.value)} /></label><label>Work email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Password<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} /></label><button disabled={busy}>{busy?"Creating...":"Create account"}</button></form><div style={s.bottom}>Already have an account? <a href="/login">Sign in</a></div></div></main>
}
const s={page:{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f7f8fa",fontFamily:"Inter,system-ui,sans-serif",padding:20},card:{width:"100%",maxWidth:410,background:"white",border:"1px solid #e3e7ed",borderRadius:14,padding:32,boxShadow:"0 12px 35px rgba(17,24,39,.06)"},logo:{fontSize:19,fontWeight:800,display:"flex",gap:9,alignItems:"center",marginBottom:32},h1:{fontSize:28,margin:"0 0 8px"},p:{color:"#6b7280",fontSize:13,margin:"0 0 24px"},error:{background:"#fff1f2",color:"#be123c",border:"1px solid #fecdd3",padding:11,borderRadius:8,fontSize:12,marginBottom:14},label:{display:"block",fontSize:11,fontWeight:700,color:"#374151",marginBottom:14},input:{display:"block",width:"100%",marginTop:6,padding:11,border:"1px solid #d9dee6",borderRadius:8,outline:"none",boxSizing:"border-box"},button:{display:"block",width:"100%",padding:12,border:0,borderRadius:8,background:"#111827",color:"white",fontWeight:700,textAlign:"center",textDecoration:"none",cursor:"pointer"},bottom:{marginTop:22,textAlign:"center",fontSize:11,color:"#6b7280"}};
