"use client";
import { useEffect, useMemo, useState } from "react";

type Lead={id:string;name:string;phone:string|null;email:string|null;service:string|null;status:string|null;"quote amount":number|null;"appointment date":string|null};
const statuses=["New","Contacted","Quoted","Scheduled","Completed","Cancelled"];

export default function LeadsPage(){
 const[leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("All"),[saving,setSaving]=useState<string|null>(null);
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/leads",{cache:"no-store"}),x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||"Unable to load leads");setLeads(x.data||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load leads")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function updateStatus(id:string,status:string){setSaving(id);setError("");try{const r=await fetch("/api/leads",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})}),x=await r.json();if(!r.ok||!x.success)throw new Error(x.error||"Unable to update lead");setLeads(v=>v.map(l=>l.id===id?{...l,status}:l))}catch(e){setError(e instanceof Error?e.message:"Unable to update lead")}finally{setSaving(null)}}
 const filtered=useMemo(()=>leads.filter(l=>{const q=search.toLowerCase().trim();const match=!q||[l.name,l.phone,l.email,l.service].some(v=>(v||"").toLowerCase().includes(q));return match&&(filter==="All"||l.status===filter)}),[leads,search,filter]);
 const stats={total:leads.length,new:leads.filter(l=>(l.status||"New")==="New").length,quoted:leads.filter(l=>l.status==="Quoted").length,scheduled:leads.filter(l=>l.status==="Scheduled").length};
 return <main style={s.page}><div style={s.container}><Header/><div style={s.header}><div><div style={s.eyebrow}>CUSTOMER PIPELINE</div><h1 style={s.title}>Leads</h1><p style={s.muted}>Manage every customer from first contact through completed job.</p></div><div style={s.actions}><button onClick={()=>void load()} style={s.secondary}>↻ Refresh</button><a href="/leads/new" style={s.button}>+ New Lead</a></div></div>{error&&<div style={s.error}>⚠ {error}<button onClick={()=>void load()} style={s.retry}>Try again</button></div>}<div style={s.stats}><Stat label="Total leads" value={stats.total}/><Stat label="New" value={stats.new}/><Stat label="Quoted" value={stats.quoted}/><Stat label="Scheduled" value={stats.scheduled}/></div><div style={s.toolbar}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by customer, phone, email, or service..." style={s.input}/><select value={filter} onChange={e=>setFilter(e.target.value)} style={s.select}><option>All</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><span style={s.count}>{filtered.length} shown</span></div><section style={s.card}>{loading?<Empty text="Loading leads..."/>:filtered.length===0?<div style={s.empty}><div style={s.emptyIcon}>+</div><h2>{leads.length?"No matching leads":"No leads yet"}</h2><p>{leads.length?"Try a different search or filter.":"Create your first customer to get started."}</p>{!leads.length&&<a href="/leads/new" style={s.button}>Create Lead</a>}</div>:<div style={{overflowX:"auto"}}><table style={s.table}><thead><tr><th>Customer</th><th>Service</th><th>Status</th><th>Quote</th><th>Appointment</th><th></th></tr></thead><tbody>{filtered.map(l=><tr key={l.id}><td><a href={`/leads/${l.id}`} style={s.customer}>{l.name}</a><div style={s.small}>{l.phone||l.email||"No contact"}</div></td><td>{l.service||"—"}</td><td><select disabled={saving===l.id} value={l.status||"New"} onChange={e=>void updateStatus(l.id,e.target.value)} style={{...s.statusSelect,...statusColor(l.status)}}>{statuses.map(x=><option key={x}>{x}</option>)}</select></td><td>{l["quote amount"]==null?"—":`$${Number(l["quote amount"]).toLocaleString()}`}</td><td>{l["appointment date"]?new Date(l["appointment date"]+"T00:00:00").toLocaleDateString():"—"}</td><td><a href={`/leads/${l.id}`} style={s.open}>Open →</a></td></tr>)}</tbody></table></div>}</section></div></main>
}
function Header(){return <nav style={s.nav}><a href="/" style={s.logo}><span style={s.logoMark}>Q</span>QuoteFlow</a><div style={s.links}><a href="/" style={s.link}>Dashboard</a><a href="/leads" style={s.active}>Leads</a><a href="/quotes" style={s.link}>Quotes</a><a href="/appointments" style={s.link}>Appointments</a></div><a href="/leads/new" style={s.button}>+ New Lead</a></nav>}
function Stat({label,value}:{label:string;value:number}){return <div style={s.stat}><span>{label}</span><strong>{value}</strong></div>}
function Empty({text}:{text:string}){return <div style={s.empty}>{text}</div>}
function statusColor(value:string|null){const x=(value||"New").toLowerCase();const colors:Record<string,object>={new:{background:"#fff7ed",color:"#c2410c"},contacted:{background:"#eff6ff",color:"#2563eb"},quoted:{background:"#f5f3ff",color:"#7c3aed"},scheduled:{background:"#f0fdf4",color:"#15803d"},completed:{background:"#ecfdf5",color:"#059669"},cancelled:{background:"#f1f5f9",color:"#64748b"}};return colors[x]||colors.new}
const s={page:{minHeight:"100vh",background:"#f7f8fa",color:"#111827",fontFamily:"Inter,ui-sans-serif,system-ui,sans-serif"},container:{maxWidth:1200,margin:"0 auto",padding:"0 28px 60px"},nav:{height:72,display:"flex",alignItems:"center",gap:28,borderBottom:"1px solid #e5e7eb"},logo:{display:"flex",alignItems:"center",gap:9,color:"#111827",textDecoration:"none",fontSize:19,fontWeight:800},logoMark:{width:30,height:30,display:"grid",placeItems:"center",borderRadius:8,background:"#111827",color:"white",fontSize:14},links:{display:"flex",justifyContent:"center",gap:26,flex:1},link:{color:"#6b7280",textDecoration:"none",fontSize:13,fontWeight:600},active:{color:"#111827",textDecoration:"none",fontSize:13,fontWeight:700,borderBottom:"2px solid #111827",paddingBottom:7},header:{display:"flex",justifyContent:"space-between",alignItems:"end",padding:"40px 0 22px"},eyebrow:{color:"#6b7280",fontSize:10,fontWeight:800,letterSpacing:1.5,marginBottom:7},title:{margin:0,fontSize:32,letterSpacing:-1},muted:{color:"#6b7280",marginTop:7,fontSize:13},actions:{display:"flex",gap:9},button:{background:"#111827",color:"white",textDecoration:"none",padding:"10px 14px",borderRadius:8,fontSize:12,fontWeight:700,border:0,cursor:"pointer"},secondary:{background:"white",border:"1px solid #d9dee6",borderRadius:8,padding:"9px 13px",cursor:"pointer",color:"#374151",fontSize:12,fontWeight:700},error:{padding:13,marginBottom:16,borderRadius:8,background:"#fff1f2",color:"#be123c",border:"1px solid #fecdd3",fontSize:12},retry:{marginLeft:10,border:0,background:"none",textDecoration:"underline",cursor:"pointer",color:"inherit"},stats:{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14,marginBottom:16},stat:{background:"white",border:"1px solid #e3e7ed",borderRadius:10,padding:"15px 17px",display:"flex",justifyContent:"space-between",alignItems:"center",color:"#6b7280",fontSize:11,fontWeight:600},toolbar:{display:"flex",gap:10,alignItems:"center",marginBottom:14},input:{flex:1,minWidth:0,padding:"11px 12px",border:"1px solid #d9dee6",borderRadius:8,fontSize:12,background:"white",outline:"none"},select:{padding:"10px 12px",border:"1px solid #d9dee6",borderRadius:8,background:"white",fontSize:12,color:"#374151"},count:{fontSize:11,color:"#9ca3af"},card:{background:"white",border:"1px solid #e3e7ed",borderRadius:10,overflow:"hidden"},table:{width:"100%",borderCollapse:"collapse",textAlign:"left"},statusSelect:{padding:"6px 9px",border:"1px solid transparent",borderRadius:999,fontSize:10,fontWeight:700},customer:{color:"#111827",textDecoration:"none",fontWeight:700,fontSize:12},small:{color:"#9ca3af",fontSize:10,marginTop:4},open:{color:"#374151",textDecoration:"none",fontSize:10,fontWeight:700},empty:{padding:"65px 20px",textAlign:"center",color:"#6b7280",fontSize:13},emptyIcon:{width:34,height:34,display:"grid",placeItems:"center",margin:"0 auto 10px",borderRadius:9,background:"#f3f4f6",color:"#6b7280",fontWeight:800}};
